// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugxfdyurqoiivkjvixoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVneGZkeXVycW9paXZranZpeG9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTQ4MzUsImV4cCI6MjA2MDM5MDgzNX0.GJpP5tW4R4u-WkziXm2-XWJrGFpDObU30PhvHObgHbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);